#!/usr/bin/env bash
# ============================================================================
# DeePloy — lib/config.sh   (deeploy export | import)
# Round-trips the unified deeploy.conf so an identical box reproduces without
# re-typing. The conf is bash-env (sectioned, commented, chmod 600) and holds
# PATHS, PUBKEYS, and SETTINGS ONLY — NEVER key material.
#
# export: read the phases' recorded decisions (state) -> write deeploy.conf.
# import: validate (no key material; required keys; pubkey format) -> load into
#         state so the install resolve-functions pick them up. The stored region
#         is reproduced deterministically; `import --rescore` re-pings to refresh
#         BAM/block-engine/shred instead.
#
# Requires: common.sh sourced (region.sh for --rescore). Path overridable.
# ============================================================================

[[ -n "${_DEEPLOY_CONFIG_SOURCED:-}" ]] && return 0
_DEEPLOY_CONFIG_SOURCED=1

config_resolve() { CONFIG_FILE="${CONFIG_FILE:-${DEEPLOY_CONF:-/opt/deeploy/deeploy.conf}}"; }

# Canonical map. "@ <Section>" lines become comment headers; "CONF_KEY state_key"
# lines map an UPPERCASE conf key to its lowercase state key. NO key material.
_config_keys() {
    cat <<'MAP'
@ Host
NODE_NAME node_name
@ Network and SSH
SSH_PORT ssh_port
@ CPU tuning
POH_CORE poh_core
XDP_CORES_COUNT xdp_cores_count
XDP_CORES xdp_cores
ISOLATED_SET isolated_set
@ NIC / retransmit
NIC_DRIVER nic_driver
RETRANSMIT_SUPPORTED retransmit_supported
RETRANSMIT_ZERO_COPY retransmit_zero_copy
@ Disk
DISK_LAYOUT disk_layout
LEDGER_DISK ledger_disk
ACCOUNTS_DISK accounts_disk
SOLANA_HOME solana_home
LEDGER_PATH ledger_path
ACCOUNTS_PATH accounts_path
SNAPSHOTS_PATH snapshots_path
@ Build
JITO_TAG jito_tag
@ Keys (PATHS ONLY — no key material; vote is a public pubkey)
UNSTAKED_KEYPAIR sync_identity
STAKED_KEYPAIR staked_keypair
VOTE_ACCOUNT_PUBKEY vote_account_pubkey
@ MEV
MEV_MODE mev_mode
BAM_URL bam_url
BLOCK_ENGINE_URL block_engine_url
SHRED_RECEIVER_ADDRESS shred_receiver
COMMISSION_BPS commission_bps
@ DoubleZero
DZ_ENABLED dz_enabled
DZ_ENV dz_env
DZ_KEYPAIR dz_keypair
MAP
}

# --- export ------------------------------------------------------------------
config_export() {
    config_resolve
    # Bridge a couple of globals into state so they're captured too.
    [[ -n "${NODE_NAME:-}" ]]   && state_set node_name "$NODE_NAME"
    [[ -n "${DZ_ENABLED:-}" ]]  && state_set dz_enabled "$DZ_ENABLED"

    local content a b v ver
    ver="$(state_get deeploy_version "$DEEPLOY_VERSION")"
    content="# DeePloy config — generated by '${DEEPLOY_CMD} export' ($(date -u '+%Y-%m-%d %H:%M:%S')Z)
# Created with DeePloy v${ver}
# PATHS, PUBKEYS, and SETTINGS only — NEVER key material. chmod 600.
# Reuse on an identical box:  ${DEEPLOY_CMD} install --config <this file>
"
    while read -r a b; do
        [[ -z "$a" ]] && continue
        if [[ "$a" == "@" ]]; then content+=$'\n'"# --- ${b} ---"$'\n'; continue; fi
        v="$(state_get "$b" "")"
        content+="${a}=\"${v}\""$'\n'
    done < <(_config_keys)

    write_file "$CONFIG_FILE" "$content" 0600
    ok "Exported config -> ${CONFIG_FILE} (paths/pubkeys/settings only; chmod 600)"
}

# --- validate (before acting) ------------------------------------------------
_config_validate() {
    local f=$1 k vote
    [[ -f "$f" ]] || { warn "config not found: $f"; return 1; }
    # Refuse anything that looks like embedded key material (a keypair is a JSON
    # array of ints, e.g. [174,12,...]).
    if grep -qE '\[[0-9]+,[0-9]+' "$f"; then
        warn "Refusing import: $f appears to contain key material (a JSON int array). Configs must hold PATHS ONLY."
        return 1
    fi
    for k in JITO_TAG SOLANA_HOME VOTE_ACCOUNT_PUBKEY; do
        grep -qE "^${k}=" "$f" || { warn "config missing required key: ${k}"; return 1; }
    done
    vote=$(awk -F'"' '/^VOTE_ACCOUNT_PUBKEY=/{print $2; exit}' "$f")
    [[ "$vote" =~ ^[1-9A-HJ-NP-Za-km-z]{32,44}$ ]] || { warn "VOTE_ACCOUNT_PUBKEY not a valid base58 pubkey: '${vote}'"; return 1; }
    return 0
}

# --- import ------------------------------------------------------------------
config_import() {
    config_resolve
    _config_validate "$CONFIG_FILE" || fail "Config validation failed — nothing imported"
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    local a b v
    while read -r a b; do
        [[ -z "$a" || "$a" == "@" ]] && continue
        v="${!a:-}"                       # value of the UPPERCASE conf global
        [[ -n "$v" ]] && state_set "$b" "$v"
    done < <(_config_keys)

    if [[ "${RESCORE:-0}" == "1" ]]; then
        if declare -F region_recommend >/dev/null; then
            info "Re-scoring region (import --rescore) — re-pinging BAM + block-engine..."
            region_recommend || warn "region scan failed — keeping stored region"
            state_set bam_url          "$(state_get suggested_bam_url "$(state_get bam_url)")"
            state_set block_engine_url "$(state_get suggested_block_engine_url "$(state_get block_engine_url)")"
            state_set shred_receiver   "$(state_get suggested_shred_receiver "$(state_get shred_receiver)")"
        else
            warn "region.sh not loaded — cannot rescore; keeping stored region"
        fi
    else
        info "Reproducing stored region deterministically: $(state_get bam_url '<none>')  (use 'import --rescore' to re-ping)"
    fi
    ok "Imported config from ${CONFIG_FILE} into state"
}
