#!/usr/bin/env bash
# ============================================================================
# DeePloy — lib/nic.sh   (NIC setup layer; runs after tuning/validatorcfg,
# Before=solana.service). Driver-specific, mandated for XDP-retransmit boxes:
#   mlx5_core -> mlx5-irq-affinity.service: pin mlx5 completion-queue IRQs to
#               align with the XDP cores and OFF the PoH core.
#   bnxt_en   -> nic-tuning.service: ring 512/512 (default 511 breaks XDP) +
#               disable gro/lro/gso/tso; then a pre-flight ZC compatibility test
#               (anza-xyz/agave-xdp-compatibility) before the validator starts.
#   other     -> nothing (retransmit already omitted).
#
# The interface is computed at RUNTIME inside the generated scripts
# (ip route show default), never hardcoded. Requires: common.sh sourced.
# ============================================================================

[[ -n "${_DEEPLOY_NIC_SOURCED:-}" ]] && return 0
_DEEPLOY_NIC_SOURCED=1

XDP_COMPAT_REPO="${XDP_COMPAT_REPO:-https://github.com/anza-xyz/agave-xdp-compatibility}"

nic_resolve_config() {
    SOLANA_HOME="$(state_get solana_home /root/solana)"
    NIC_DRIVER="$(state_get nic_driver "${NIC_DRIVER:-}")"
    MLX5_IRQ_SCRIPT="${MLX5_IRQ_SCRIPT:-$SOLANA_HOME/mlx5-irq-affinity.sh}"
    MLX5_IRQ_SERVICE="${MLX5_IRQ_SERVICE:-/etc/systemd/system/mlx5-irq-affinity.service}"
    NIC_TUNING_SCRIPT="${NIC_TUNING_SCRIPT:-$SOLANA_HOME/nic-tuning.sh}"
    NIC_TUNING_SERVICE="${NIC_TUNING_SERVICE:-/etc/systemd/system/nic-tuning.service}"
    XDP_COMPAT_SRC="${XDP_COMPAT_SRC:-$HOME/agave-xdp-compatibility}"
}

# --- mlx5: completion-queue IRQ affinity -------------------------------------
# Layout hardcoded for PoH=10, XDP cores 1-2 (identical fleet). The mapping pins
# comp queues to CPUs, moving comp10 off the PoH core (-> 11) and comp25-28 off
# the XDP HT siblings (-> 7,8,9,12).
_nic_render_mlx5_irq_script() {
    cat <<'EOF'
#!/bin/bash
# Generated by DeePloy. Align mlx5 completion-queue IRQs with the XDP cores and
# OFF the PoH core. Interface computed at runtime (not hardcoded).
# TODO: compute MAP dynamically from POH_CORE + the reserved XDP set. Pinned to
# the working PoH=10 / XDP=1-2 layout for now (fleet is identical; IRQ math is
# easy to get wrong by hand).
set -uo pipefail
NIC=$(ip route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')
[ -z "$NIC" ] && { logger -t mlx5-irq "no default-route NIC"; exit 1; }

# comp_queue_index:target_cpu
MAP="0:0 1:1 2:2 3:3 4:4 10:11 25:7 26:8 27:9 28:12"

pin() {
    local idx=$1 cpu=$2 irq
    irq=$(awk -v want="mlx5_comp${idx}@" -v nic="${NIC}-${idx}" \
        '$NF ~ want || $NF == nic {gsub(":","",$1); print $1; exit}' /proc/interrupts)
    [ -z "$irq" ] && { logger -t mlx5-irq "comp${idx}: irq not found"; return 0; }
    if echo "$cpu" > "/proc/irq/${irq}/smp_affinity_list" 2>/dev/null; then
        logger -t mlx5-irq "comp${idx} irq${irq} -> cpu${cpu}"
    else
        logger -t mlx5-irq "comp${idx} irq${irq}: failed to set cpu${cpu}"
    fi
}

for pair in $MAP; do pin "${pair%:*}" "${pair#*:}"; done
exit 0
EOF
}

_nic_render_mlx5_service() {
    cat <<EOF
[Unit]
Description=Align mlx5 completion-queue IRQs with XDP cores (off the PoH core)
After=network.target
Before=solana.service

[Service]
Type=oneshot
ExecStart=${MLX5_IRQ_SCRIPT}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
}

nic_mlx5_setup() {
    step "mlx5 IRQ-affinity service (Before=solana.service)"
    write_file "$MLX5_IRQ_SCRIPT"  "$(_nic_render_mlx5_irq_script)" 0755
    write_file "$MLX5_IRQ_SERVICE" "$(_nic_render_mlx5_service)"
    run systemctl daemon-reload
    run systemctl enable mlx5-irq-affinity.service
    ok "mlx5-irq-affinity.service installed + enabled"
}

# --- bnxt_en: ring + offload tuning ------------------------------------------
_nic_render_bnxt_script() {
    cat <<'EOF'
#!/bin/bash
# Generated by DeePloy. bnxt_en ring + offload tuning for XDP. Interface
# computed at runtime (not hardcoded).
set -uo pipefail
NIC=$(ip route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')
[ -z "$NIC" ] && { logger -t nic-tuning "no default-route NIC"; exit 1; }
# Default rx/tx ring of 511 breaks XDP; bump to 512.
ethtool -G "$NIC" rx 512 tx 512 || logger -t nic-tuning "ring resize failed on $NIC"
# XDP needs these offloads disabled.
ethtool -K "$NIC" gro off lro off gso off tso off || logger -t nic-tuning "offload disable failed on $NIC"
logger -t nic-tuning "tuned $NIC (rings 512/512; gro/lro/gso/tso off)"
exit 0
EOF
}

_nic_render_bnxt_service() {
    cat <<EOF
[Unit]
Description=bnxt_en NIC ring + offload tuning for XDP
After=network.target
Before=solana.service

[Service]
Type=oneshot
ExecStart=${NIC_TUNING_SCRIPT}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
}

# Pre-flight ZC compatibility test: verify the ring fix took before starting.
nic_bnxt_xdp_test() {
    step "bnxt_en XDP pre-flight (agave-xdp-compatibility against 8.8.8.8)"
    if is_dry_run; then
        info "${C_DIM}[dry-run]${C_NC} would clone+build ${XDP_COMPAT_REPO}, setcap, and test XDP against 8.8.8.8"
        return 0
    fi
    [[ -d "$XDP_COMPAT_SRC" ]] && run rm -rf "$XDP_COMPAT_SRC"
    run git clone "$XDP_COMPAT_REPO" "$XDP_COMPAT_SRC"
    if ! ( cd "$XDP_COMPAT_SRC" && cargo build --release ); then
        warn "agave-xdp-compatibility build failed — cannot verify XDP; do not start until resolved"
        return 1
    fi
    local bin nic
    bin=$(find "$XDP_COMPAT_SRC/target/release" -maxdepth 1 -type f -perm -u+x ! -name '*.d' 2>/dev/null | head -1)
    [[ -n "$bin" ]] || { warn "xdp-compat binary not found after build"; return 1; }
    run setcap cap_net_admin,cap_net_raw,cap_bpf,cap_perfmon+ep "$bin"
    nic=$(ip route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')
    # IP positional, interface as --xdp-interface, plus --timeout-ms (prod CLI).
    if "$bin" 8.8.8.8 --xdp-interface "$nic" --timeout-ms 1000; then
        ok "bnxt_en XDP verified (ring fix took)"
    else
        warn "bnxt_en XDP test FAILED — the ring/offload fix did not take. Do not start the validator."
        return 1
    fi
}

nic_bnxt_setup() {
    step "bnxt_en NIC tuning service (Before=solana.service)"
    write_file "$NIC_TUNING_SCRIPT"  "$(_nic_render_bnxt_script)" 0755
    write_file "$NIC_TUNING_SERVICE" "$(_nic_render_bnxt_service)"
    run systemctl daemon-reload
    run systemctl enable nic-tuning.service
    # ORDER MATTERS: apply the ring fix (rx 512) NOW, BEFORE the ZC pre-flight
    # test — with the default ring of 511 the XDP test always fails.
    run bash "$NIC_TUNING_SCRIPT"
    ok "nic-tuning.service installed + enabled (ring fix applied)"
    nic_bnxt_xdp_test || warn "Proceeding, but XDP is unverified on this bnxt_en box"
}

# --- orchestrator ------------------------------------------------------------
nic_run() {
    require_root
    nic_resolve_config
    case "$NIC_DRIVER" in
        mlx5_core) nic_mlx5_setup ;;
        bnxt_en)   nic_bnxt_setup ;;
        "")        warn "NIC driver unknown — skipping NIC-setup layer" ;;
        *)         info "No NIC-setup service for driver '${NIC_DRIVER}' (retransmit disabled)" ;;
    esac
}
